theme: minima
title: normal title
author: Chong Hok Kan
email: 1155159055@link.cuhk.edu.hk
description: > # this means to ignore newlines until "baseurl:"
  I am Chong Hok Kan.

# social links
twitter_username: no # DO NOT include the @ character, or else the build will fail!
github_username:  ChongHokKan # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
 
theme: minima
